### ISSUE TITLE
Allow khal to start without a configuration

### ISSUE THREAD

**Issue by johannes-darms** [geier/khal#269] opened 2015-09-23 13:09 UTC
After a fresh installation khal does not start. It complains about a missing configuration file. It would be better to start khal with an empty calender, as most other GUI Applications do, and some sane defaults. This would lower the entrance barrier for new users. Additional it would allow the use of khal as an local only calender.

**Comment by geier** [comment] 2015-09-23 14:37
I'll close this as a duplicate of #55. Any help on this is very welcome though.

**Closed by geier** 2015-09-23 14:37 UTC
