### ISSUE TITLE
khal does not show all calendars

### ISSUE THREAD

**Issue by matthiasbeyer** [geier/khal#156] opened 2015-02-08 14:53 UTC
I'm sorry to (kind of) re-report this. Maybe I'm to stupid, but maybe it is a bug:

```bash
$ khal calendar
```

gives me only entries from one calendar. Doing

```bash
$ khal calendar -a holidays
```

Gives me nothing, but there are (in my owncloud) entries.

My Config:

```
[calendars]
[[personal]]
path = ~/archive/calendar.vdirsyncer/personal/
color = dark blue
readonly = False

[[birthdays]]
path = ~/archive/calendar.vdirsyncer/contact_birthdays/
color = dark green
readonly = True

[[holidays]]
path = ~/archive/calendar.vdirsyncer/holidays/
color = yellow
readonly = False

[[studying]]
path = ~/archive/calendar.vdirsyncer/studying/
color = dark red
readonly = False

[sqlite]
path = ~/.khal/khal.db

[locale]
local_timezone = Europe/Berlin
default_timezone = Europe/Berlin

timeformat = %H:%M
dateformat = %d.%m.
longdateformat = %d.%m.%Y
datetimeformat =  %d.%m. %H:%M
longdatetimeformat = %d.%m.%Y %H:%M

firstweekday = 0

[default]
default_command = calendar
default_calendar = personal
# in agenda/calendar display, shows all days even if there is no event
#show_all_days = False
#debug = 0

```

copied 1-1! All paths are correct, I triple-checked them. I also `grep`ed over the calendar directory, all `.ics` files are there, so the `vdirsyncer` did its job well.

**Comment by untitaker** [comment] 2015-02-08 15:03
Hmm, I can't reproduce this. Which version are you using? The PyPI package is working as well as the git version for me.

**Comment by matthiasbeyer** [comment] 2015-02-08 15:30
```bash
$ khal --version
khal, version 0.4.0.dev-149-gce070ec
```

**Comment by geier** [comment] 2015-02-09 07:14
does khal only show events from one khalendar or is only one calendar missing?

and please do report anything that is not working. If it turns out something like that is a misconfiguration, there is something wrong with khal, as it should be easy to see when its misconfigured.

**Comment by matthiasbeyer** [comment] 2015-02-09 09:16
It does only show events from one calendar.

**Comment by geier** [comment] 2015-02-09 09:37
Could you have a look at the sqlite database? (e.g. by installing sqlitebrowser, and then running `sqlitebrowser ~/.khal/khal.db` ) Have a look at the `recs_loc` and `recs_float` table and see if there are entries belonging to those calendars you are missing (the name in the `calendar` column should match, `dtstart` and `dtend` are in unix time).

I'm sorry to have to involve you in the debugging process, but since I cannot reproduce the issue locally, I don't see another way.

**Comment by matthiasbeyer** [comment] 2015-02-17 10:35
Strange. I cannot reproduce now.

**Comment by untitaker** [comment] 2015-02-17 10:44
Maybe the real problem was that khal skipped a lot of events it didn't understand? Although that should create warnings.

**Comment by matthiasbeyer** [comment] 2015-02-17 10:48
I'm not sure about this. I'd like to suggest leaving this issue open until I'm certain about either the cause or how to reproduce, if you're fine with this!

**Comment by geier** [comment] 2015-02-17 16:21
Alright, will leave this open, please report if the error occurs again.

**Comment by matthiasbeyer** [comment] 2015-07-13 15:22
I can reproduce again. I do not get _any_ calendar entries with khal 0.5.0 now. The `ical` files are clearly there. 0.4.0 doesn't work, either.

**Comment by untitaker** [comment] 2015-07-13 16:19
Could you post an item that is not shown in khal?

**Comment by matthiasbeyer** [comment] 2015-07-13 16:21
Sure:

```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:ownCloud Calendar 0.6.4
BEGIN:VEVENT
UID:rem2ics.54ccca77.7f39.10@localhost
SUMMARY:Fronleichnam
DTSTART;VALUE=DATE:20150604
DTEND;VALUE=DATE:20150605
DTSTAMP;VALUE=DATE-TIME:20150201T110837Z
COMMENT: generated by rem2ics 0.93\n http://mark.atwood.name/code/rem2ics\n
  data[16]=|2015/06/04 * * * * Fronleichnam|
RRULE:FREQ=YEARLY;INTERVAL=1
LAST-MODIFIED;VALUE=DATE-TIME:20150201T110837Z
CLASS:PUBLIC
END:VEVENT
END:VCALENDAR
```

German feast day.

Anotherone:

```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:ownCloud Calendar
BEGIN:VEVENT
CREATED;VALUE=DATE-TIME:20150527T160029Z
UID:4e34083ac0
LAST-MODIFIED;VALUE=DATE-TIME:20150527T160029Z
DTSTAMP;VALUE=DATE-TIME:20150527T160029Z
SUMMARY:Soilwork Album release
DTSTART;VALUE=DATE:20150828
DTEND;VALUE=DATE:20150829
END:VEVENT
END:VCALENDAR
```

**Comment by untitaker** [comment] 2015-07-13 16:37
Just to be clear, where do you expect khal to show them?

**Comment by matthiasbeyer** [comment] 2015-07-13 16:44
Ah, of course, maybe I should've provided a calendar entry which gets shown anytime soon, right?

Here is one:

```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:ownCloud Calendar
BEGIN:VEVENT
CREATED;VALUE=DATE-TIME:20150612T185333Z
UID:01934cdcaf
LAST-MODIFIED;VALUE=DATE-TIME:20150612T185357Z
DTSTAMP;VALUE=DATE-TIME:20150612T185357Z
SUMMARY:Lamb of God - VII: Sturm und Drang
DTSTART;VALUE=DATE:20150724
DTEND;VALUE=DATE:20150725
CLASS:PUBLIC
END:VEVENT
END:VCALENDAR
```

This one should be on 24. of this month, so it should show up in khal... I guess?

**Comment by untitaker** [comment] 2015-07-13 16:47
That depends on which part of khal you use. `khal agenda` doesn't show any of those events for me because they're not in range yet, but I can find them when opening `ikhal` and navigating to their dates.

**Comment by matthiasbeyer** [comment] 2015-07-13 16:56
Okay. `ikhal` shows them for me as well. (speaking of 0.4.0 now)

But two things: 

1. I have a recurring event "Work" every day until end of this month. It isn't shown at all.
2. I have no visual feedback in the calendar of `ikhal`. It just lists the dates, but the days are in normal color, even if there is an event.

Normal khal does not show the "Lamb of God" event at all:

```bash
$ khal agenda -a musicreleases
No events
```

or with `calendar` instead of `agenda`.

---

The above also applies for v0.5.0 of khal.

**Comment by untitaker** [comment] 2015-07-13 17:01
Right, I see why you'd expect `agenda` to show these, at the moment it only previews a fixed amount of days: two.

Related issues: https://github.com/geier/khal/issues/93 and https://github.com/geier/khal/issues/89

I'm going to close this for now since there's no bug, just stupid behavior. I think the misleading name of the `agenda` command is already tracked with #93.

**Closed by untitaker** 2015-07-13 17:01 UTC
Labels: bug, cannot reproduce, needs info
