### ISSUE TITLE
Crash (ikhal)

### ISSUE THREAD

**Issue by josswright** [geier/khal#351] opened 2016-02-23 10:40 UTC
Using the latest git checkout, through khal-git in the AUR, I get a crash when trying to browse to the 29th February in ikhal. When trying to add an event directly using "khal new 29.02. ..." I get a "Cannot parse: '29.02. ...' error.

My default_timezone and local_timezone are set to 'GB'.
```
Traceback when using ikhal:
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/khal/ui/__init__.py", line 891, in start_pane
    loop.run()
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 719, in _loop
    self._watch_files[fd]()
  File "/usr/lib/python3.5/site-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/lib/python3.5/site-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/lib/python3.5/site-packages/urwid/wimp.py", line 643, in keypress
    return self._current_widget.keypress(size, key)
  File "/usr/lib/python3.5/site-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/lib/python3.5/site-packages/khal/ui/__init__.py", line 728, in keypress
    return super().keypress(size, key)
  File "/usr/lib/python3.5/site-packages/urwid/container.py", line 2269, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/usr/lib/python3.5/site-packages/urwid/container.py", line 1587, in keypress
    key = self.focus.keypress(tsize, key)
  File "/usr/lib/python3.5/site-packages/urwid/container.py", line 2269, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/usr/lib/python3.5/site-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/lib/python3.5/site-packages/khal/ui/calendarwidget.py", line 327, in keypress
    key = super(CListBox, self).keypress(size, key)
  File "/usr/lib/python3.5/site-packages/urwid/listbox.py", line 985, in keypress
    key = focus_widget.keypress((maxcol,),key)
  File "/usr/lib/python3.5/site-packages/khal/ui/calendarwidget.py", line 178, in keypress
    key = super(DateCColumns, self).keypress(size, key)
  File "/usr/lib/python3.5/site-packages/urwid/container.py", line 2283, in keypress
    self.focus_position = j
  File "/usr/lib/python3.5/site-packages/khal/ui/calendarwidget.py", line 139, in _set_focus_position
    self.on_date_change(self.contents[position][0].date)
  File "/usr/lib/python3.5/site-packages/khal/ui/__init__.py", line 764, in show_date
    self.eventscolumn.original_widget.current_date = date
  File "/usr/lib/python3.5/site-packages/khal/ui/__init__.py", line 307, in current_date
    self.eventcount = self.events.update_by_date(date)
  File "/usr/lib/python3.5/site-packages/khal/ui/__init__.py", line 243, in update_by_date
    'calendar ' + event.calendar, 'reveal focus') for event in events]
  File "/usr/lib/python3.5/site-packages/khal/ui/__init__.py", line 243, in <listcomp>
    'calendar ' + event.calendar, 'reveal focus') for event in events]
  File "/usr/lib/python3.5/site-packages/khal/ui/__init__.py", line 64, in __init__
    text = self.event.relative_to(self.this_date)
  File "/usr/lib/python3.5/site-packages/khal/khalendar/event.py", line 414, in relative_to
    body = self.summary
  File "/usr/lib/python3.5/site-packages/khal/khalendar/event.py", line 343, in summary
    bday = self._vevents[self.ref].get('x-birthday', None)
KeyError: '1456704000'
```

**Comment by hobarrera** [comment] 2016-02-23 11:03
Looks like it's the same issue as #348

**Comment by geier** [comment] 2016-02-23 13:16
I'd like to split this into two reports, as it looks like two different issues.

**Comment by geier** [comment] 2016-02-23 13:17
see #353 for the Feb 29 issues.

**Comment by geier** [comment] 2016-03-06 21:07
and yes, the other part is a duplicate of #348. Closing as duplicate.

**Closed by geier** 2016-03-06 21:07 UTC
Labels: bug
