### ISSUE TITLE
VALARM support

### ISSUE THREAD

**Issue by mbaldessari** [geier/khal#167] opened 2015-02-18 08:56 UTC
Hi Christian,

so I am almost done with dropping my web Zimbra interface usage in favour of khal ;) I am missing
one thing: notifications for upcoming events.

I was about to script something via "khal agenda --days 1" piped to a python script which will then 
notify me somehow (via notify-send or something similar), but then I realized that most of my .ics
files already have data that specifies when and how I should be notified. For example:
```
BEGIN:VALARM
ACTION:DISPLAY
TRIGGER;RELATED=START:-PT5M
DESCRIPTION:Reminder
END:VALARM
```

It would be extremely cool to have something (just thinking aloud here) like:
`khal alarms --script foo --delta 60min` which will call `foo` for every event that will take place
in the next 60 minutes (passing the subject of the event + time as args). That way it could
be put in a cron job pretty easily.

Or something close to that concept anyway ;) 

Regards,
Michele

**Comment by geier** [comment] 2015-02-18 14:24
I'm going to close this as a duplicate of #148 and copy your usage idea over there

**Closed by geier** 2015-02-18 14:24 UTC
