### ISSUE TITLE
Ikhal dies on imported event

### ISSUE THREAD

**Issue by benv666** [geier/khal#348] opened 2016-02-22 10:09 UTC
I just imported a new ics file (attached to this issue).
[1.ics.txt](https://github.com/geier/khal/files/140396/1.ics.txt)
When I try to view the date the event is on in ikhal it dies:
```
Traceback (most recent call last):                                                                                                                                                       [4/22]
  File "/usr/lib64/python3.5/site-packages/khal/ui/__init__.py", line 896, in start_pane
    loop.run()
  File "/usr/lib64/python3.5/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib64/python3.5/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib64/python3.5/site-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/usr/lib64/python3.5/site-packages/urwid/main_loop.py", line 719, in _loop
    self._watch_files[fd]()
  File "/usr/lib64/python3.5/site-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/lib64/python3.5/site-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib64/python3.5/site-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/usr/lib64/python3.5/site-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/lib64/python3.5/site-packages/urwid/wimp.py", line 643, in keypress
    return self._current_widget.keypress(size, key)
  File "/usr/lib64/python3.5/site-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/lib64/python3.5/site-packages/khal/ui/__init__.py", line 733, in keypress
    return super().keypress(size, key)
  File "/usr/lib64/python3.5/site-packages/urwid/container.py", line 2269, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/usr/lib64/python3.5/site-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/lib64/python3.5/site-packages/khal/ui/calendarwidget.py", line 327, in keypress
    key = super(CListBox, self).keypress(size, key)
  File "/usr/lib64/python3.5/site-packages/urwid/listbox.py", line 985, in keypress
    key = focus_widget.keypress((maxcol,),key)
  File "/usr/lib64/python3.5/site-packages/khal/ui/calendarwidget.py", line 178, in keypress
    key = super(DateCColumns, self).keypress(size, key)
  File "/usr/lib64/python3.5/site-packages/urwid/container.py", line 2283, in keypress
    self.focus_position = j
  File "/usr/lib64/python3.5/site-packages/khal/ui/calendarwidget.py", line 139, in _set_focus_position
    self.on_date_change(self.contents[position][0].date)
  File "/usr/lib64/python3.5/site-packages/khal/ui/__init__.py", line 769, in show_date
    self.eventscolumn.original_widget.current_date = date
  File "/usr/lib64/python3.5/site-packages/khal/ui/__init__.py", line 307, in current_date
    self.eventcount = self.events.update_by_date(date)
  File "/usr/lib64/python3.5/site-packages/khal/ui/__init__.py", line 243, in update_by_date
    'calendar ' + event.calendar, 'reveal focus') for event in events]
  File "/usr/lib64/python3.5/site-packages/khal/ui/__init__.py", line 243, in <listcomp>
    'calendar ' + event.calendar, 'reveal focus') for event in events]
  File "/usr/lib64/python3.5/site-packages/khal/ui/__init__.py", line 64, in __init__
    text = self.event.relative_to(self.this_date)
  File "/usr/lib64/python3.5/site-packages/khal/khalendar/event.py", line 414, in relative_to
    body = self.summary
  File "/usr/lib64/python3.5/site-packages/khal/khalendar/event.py", line 343, in summary
    bday = self._vevents[self.ref].get('x-birthday', None)
KeyError: '1459490400'

```

**Comment by geier** [comment] 2016-02-22 21:50
Thank you for reporting this. I do believe this is a duplicate of https://github.com/geier/khal/issues/323. What server did you get this from?

**Comment by benv666** [comment] 2016-02-23 07:37
This was from the exchange / office365 setup from work. Not sure if there's any specific version info, but if you want to see specific mail headers I can look for them :)

**Comment by josswright** [comment] 2016-02-23 11:13
Just coming across from issue #351 -- I have a personal radicale calendar and a work exchange server calendar being synchronised via vdirsyncer. (No Google calendars here, as mentioned in #323 .)

**Comment by geier** [comment] 2016-03-06 21:08
This is indeed a duplicate of #323, I'll need to re-read the RFC if those icalendar files are indeed valid and what can be done about that.

**Closed by geier** 2016-03-06 21:08 UTC
Labels: bug
