### ISSUE TITLE
colouring day number if it has event

### ISSUE THREAD

**Issue by quite** [geier/khal#163] opened 2015-02-16 08:26 UTC
For me, day numbers (interactive or otherwise) does not have a special colour even if there is a calendar event on that day. Only today and currently selected day has a colour. Is this correct, or is there something wrong with my system?

**Comment by untitaker** [comment] 2015-02-16 09:01
That's correct.

**Comment by geier** [comment] 2015-02-16 10:38
Do you mean in ikhal or in khal? If it is khal, this is a duplicate of #89

**Comment by untitaker** [comment] 2015-02-16 10:39
Ah, let's use one ticket for both.

**Closed by untitaker** 2015-02-16 10:39 UTC
Labels: enhancement

**Comment by quite** [comment] 2015-02-16 10:51
Correct.
