### ISSUE TITLE
DTSTART has invalid or incomprehensible timezone information

### ISSUE THREAD

**Issue by hobarrera** [geier/khal#328] opened 2016-01-19 02:08 UTC
Each time I delete `khal.db`, I'm getting the below warning for very large amount of events:

```
warning: DTSTART has invalid or incomprehensible timezone information in DQE3VNH8WVVCAES1LT1ZIMRUL8FC8STNFBT0.ics in personal
warning: DTEND has invalid or incomprehensible timezone information in DQE3VNH8WVVCAES1LT1ZIMRUL8FC8STNFBT0.ics in personal
```

Here's a sample one:

```
BEGIN:VCALENDAR
PRODID:-//Radicale//NONSGML Radicale Server//EN
VERSION:2.0
BEGIN:VTIMEZONE
TZID:local
X-RADICALE-NAME:local
BEGIN:STANDARD
DTSTART;VALUE=DATE-TIME:20090314T230000
TZNAME:ART
TZOFFSETFROM:-0200
TZOFFSETTO:-0300
X-RADICALE-NAME:local
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
SUMMARY:Credicoop
DTSTART;TZID="local;VALUE=DATE-TIME":20150320T120000
DTEND;TZID="local;VALUE=DATE-TIME":20150320T130000
DTSTAMP;VALUE=DATE-TIME:20150320T233047Z
UID:DQE3VNH8WVVCAES1LT1ZIMRUL8FC8STNFBT0
SEQUENCE:0
X-RADICALE-NAME:DQE3VNH8WVVCAES1LT1ZIMRUL8FC8STNFBT0.ics
END:VEVENT
END:VCALENDAR
```

**Comment by geier** [comment] 2016-01-19 10:14
Are the quotation marks really like this in the .ics file (for DTSTART and DTEND)? If so, icalendar expects the timezone to be `local;VALUE=DATE-TIME`, but there is only is a `local` timezone defined.

**Comment by hobarrera** [comment] 2016-01-19 11:32
Yes, those weirdly-placed quotations marks are there. It did look odd to me, but I wasn't sure.  
Is this icalendar file misgenerated? Should I report this to the creating app? (probably, fastmail's mobile app).

**Comment by geier** [comment] 2016-01-19 11:46
Quoting Hugo Osvaldo Barrera (2016-01-19 12:32:56)
> Yes, those weirdly-placed quotations marks are there. It did look odd to me, but I wasn't sure.  
> Is this icalendar file misgenerated? Should I report this to the creating app? (probably, fastmail's mobile app).

I'll have to take a look at the RFC, but I don't believe that they are
allowed like that.

**Comment by geier** [comment] 2016-01-19 22:25
I have concluded that those DTEND parameters are invalid. You probably should report to the creating app.

**Comment by geier** [comment] 2016-02-15 17:20
And I'll close it, as it's not a bug (at least not in khal or in icalendar), but a malformed icalendar file.

**Closed by geier** 2016-02-15 17:20 UTC
Labels: bug
